package com.parking;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.*;


public class WorkFram extends JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * @param args the command line arguments
     */
    // 变量声明 - 不进行修改//GEN-BEGIN:variables
	
    private JButton jbtnEnter;
    
    private JButton jbtnRefrush;
    
    private JTextArea jtexInfor;
    
    public int m_areaCount; //停车区个数
    
    public int[] m_nos;     //每个停车区的车位数
    
    public int[] m_apare;   //每个停车区的空闲车位数
    
    //  变量声明结束//GEN-END:variables
    //int m_areaCount;
    
    /** Creates new form WotkFram */
    
    public WorkFram(InitFrame frm) {
    	
    	this.m_areaCount = frm.m_Area.length;
        this.m_apare = new int[m_areaCount];
        this.m_nos = new int[m_areaCount];
        for(int i = 0; i < m_areaCount; i++){
            this.m_apare[i] = frm.m_Area[i];
            this.m_nos[i] = frm.m_Area[i];
        }
    	
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" 生成的代码 ">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        jbtnEnter = new JButton();
        
        jbtnRefrush = new JButton();
        
        jtexInfor = new JTextArea("停车场初始化结果：\n" + getStopStatus());
        
        jtexInfor.setEnabled(false);
       
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
        setTitle("\u505c\u8f66\u573a\u6a21\u62df");
        
        jbtnEnter.setText("\u8fdb\u5165\u505c\u8f66\u573a");
        
        jbtnRefrush.setText("刷新");
        
        jbtnEnter.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbtnEnterActionPerformed(evt);
            }
        });
        
        jbtnRefrush.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jbtnRefrushActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        
        getContentPane().setLayout(layout);
        
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jtexInfor)
                .addComponent(jbtnRefrush)
                .addComponent(jbtnEnter)               
                .addGap(128, 128, 128))
        );
        
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(jtexInfor)
                .addComponent(jbtnRefrush)
                .addComponent(jbtnEnter)
                .addGap(73, 73, 73))
        );
        
        pack();
        
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEnterActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbtnEnterActionPerformed
// TODO 将在此处添加您的处理代码：
        Thread thr = new carThread(this);
        thr.run();
    }//GEN-LAST:event_jbtnEnterActionPerformed
    
    private void jbtnRefrushActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jbtnEnterActionPerformed
//    	 TODO 将在此处添加您的处理代码：
    	this.jtexInfor.setText("停车场当前车区车位状况统计：\n" + getStopStatus());        
    }//GEN-LAST:event_jbtnEnterActionPerformed
    
    public String getStopStatus() {
    	String str = "";
    	for (int i = 0; i < m_areaCount; i++) {
    		if (m_apare[i] > 0) {
    			str += "  " + (i + 1) + " 区总车位：" + m_nos[i] + "\t当前空闲车位 " + m_apare[i] + " 个\n";
    		} else {
    			str += "  " + (i + 1) + " 区总车位：" + m_nos[i] + "\t当前区无空闲车位\n";
    		}   		
    	}
    	return str;
    }
    
    public void setInfor(String infor) {
    	this.jtexInfor.setText(infor);
    }
    
}
